"""Check a wall generated by Bonsai's own wall generator from a Hemy type."""

from pathlib import Path
import sys
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import bpy
import bonsai.tool as tool
from bonsai.bim.module.model.wall import DumbWallGenerator
import hemy_ifc_panel as panel

assert panel.bl_info["version"] >= (0, 4, 2), panel.__file__
assert bpy.ops.bim.create_project() == {"FINISHED"}
model = tool.Ifc.get()
assert model.schema == "IFC4"
props = bpy.context.scene.hemy_wall_authoring
props.image_path = str(ROOT / "qa" / "wall-authoring-sample.png")
props.type_name = "Wall Tool Material QA"
assert bpy.ops.hemy.preset_wall_layers() == {"FINISHED"}
props.confirmed = True
assert bpy.ops.hemy.create_wall_type() == {"FINISHED"}
wall_type = next(item for item in model.by_type("IfcWallType") if item.Name == props.type_name)

obj = DumbWallGenerator(wall_type).generate()
assert obj is not None
entity = tool.Ifc.get_entity(obj)
assert entity is not None and entity.IsTypedBy[0].RelatingType == wall_type
print("HEMY_AUTO_SYNC_QUEUED", bpy.app.timers.is_registered(panel.wall_authoring._run_queued_sync))
panel.wall_authoring._run_queued_sync()
assert obj.data.materials and obj.data.materials[0].get("hemy_ifc_type_guid") == wall_type.GlobalId
assert obj.data.materials[0].node_tree.nodes.get("Image Texture").image.packed_file
assert obj.data.uv_layers

# A door opening makes Bonsai replace wall mesh data. Exercise that refresh
# path with a mesh-only depsgraph update and missing material slots/UVs.
old_mesh = obj.data
replacement = old_mesh.copy()
replacement.materials.clear()
while replacement.uv_layers:
    replacement.uv_layers.remove(replacement.uv_layers[0])
if "hemy_material_type_guid" in replacement:
    del replacement["hemy_material_type_guid"]
obj.data = replacement
panel.wall_authoring._queue_sync_after_object_change(
    bpy.context.scene, SimpleNamespace(updates=[SimpleNamespace(id=replacement)]))
assert bpy.app.timers.is_registered(panel.wall_authoring._run_queued_sync)
panel.wall_authoring._run_queued_sync()
assert replacement.materials[0].get("hemy_ifc_type_guid") == wall_type.GlobalId
assert replacement.uv_layers
assert replacement.get("hemy_material_type_guid") == wall_type.GlobalId
assert panel.wall_authoring.sync_wall_materials() == 0
print("HEMY_BONSAI_WALL_TOOL_PASSED", entity.GlobalId)
